apiVersion: v1
kind: Pod
metadata:
  name: test-pod
  namespace: default
  labels:
    app: test-app
spec:
  containers:
  - name: test-container
    image: nginx:latest
    command: ["sh", "-c"]
    args: ["echo 'Hello from Pod!' && sleep 300"]
    ports:
    - containerPort: 80
      protocol: TCP
    resources:
      requests:
        cpu: 0.1
        memory: 64Mi
      limits:
        cpu: 0.5
        memory: 128Mi
  volumes:
  - name: test-volume
    hostPath:
      path: /tmp/test-data
