apiVersion: v1
kind: Service

metadata:
  name: hello-world-service
  namespace: default
  labels:
    app: hello-world

spec:
  type: ClusterIP
  selector:           # 通过 Labels 筛选 Pod
    app: hello-world
  ports:
  - name: http
    port: 80          # 集群内访问 Service 的端⼝
    targetPort: 9090  # pod实际提供服务的端⼝
    protocol: TCP

